import { Box, Heading, Text, VStack } from '@chakra-ui/react';

function TermsOfService() {
    return (
        <Box p={8} maxW="4xl" mx="auto">
            <Heading mb={4}>Terms of Service</Heading>
            <VStack align="start" spacing={4} fontSize="md">
                <Text>
                    Welcome to Vivamind. These Terms of Service ("Terms") govern your access to and use of Vivamind, including all content, features, and services provided by Vivamind ("we," "us," or "our"). By accessing or using Vivamind, you agree to be bound by these Terms. If you do not agree to all the Terms, do not use Vivamind.
                </Text>

                <Text><strong>1. Eligibility</strong></Text>
                <Text>
                    You must be at least 13 years old to use Vivamind. By using the platform, you represent and warrant that you meet this requirement.
                </Text>

                <Text><strong>2. Account Responsibilities</strong></Text>
                <Text>
                    You are responsible for maintaining the confidentiality of your account credentials and for any activity that occurs under your account. Vivamind is not liable for any loss or damage resulting from unauthorized access to your account.
                </Text>

                <Text><strong>3. Use of Services</strong></Text>
                <Text>
                    You agree not to misuse Vivamind, including but not limited to:
                    <ul>
                        <li>Posting harmful, threatening, or discriminatory content</li>
                        <li>Attempting to access other users’ data or personal information</li>
                        <li>Using the AI chat or journaling tools for illegal or abusive purposes</li>
                    </ul>
                    Vivamind reserves the right to terminate access if these terms are violated.
                </Text>

                <Text><strong>4. Content Ownership</strong></Text>
                <Text>
                    You retain ownership of any content you submit or create on Vivamind. By using the service, you grant us a non-exclusive, royalty-free, worldwide license to host, store, and display that content solely to operate and improve the service.
                </Text>

                <Text><strong>5. Payment Terms</strong></Text>
                <Text>
                    For premium features, Vivamind may charge a one-time or subscription fee. By purchasing a premium plan, you agree to provide accurate payment details and authorize us to charge the associated amount.
                </Text>

                <Text><strong>6. Refund Policy</strong></Text>
                <Text>
                    All payments are final. Refunds may be issued at our sole discretion under specific circumstances, such as technical failure or duplicate charges.
                </Text>

                <Text><strong>7. Data & Privacy</strong></Text>
                <Text>
                    Please refer to our <a href="/privacy" style={{ color: 'teal' }}>Privacy Policy</a> for how we collect, use, and protect your information. You acknowledge that no system is completely secure and agree to use Vivamind at your own risk.
                </Text>

                <Text><strong>8. AI Limitations</strong></Text>
                <Text>
                    Vivamind provides AI companions for emotional support and reflection, not for medical or professional advice. You acknowledge that all responses are generated by AI and should not replace licensed mental health services.
                </Text>

                <Text><strong>9. Termination</strong></Text>
                <Text>
                    We may suspend or terminate your access to Vivamind at any time, with or without notice, if we believe you have violated these Terms or are creating risk for us or other users.
                </Text>

                <Text><strong>10. Limitation of Liability</strong></Text>
                <Text>
                    Vivamind is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages resulting from your use of the platform.
                </Text>

                <Text><strong>11. Modifications to Terms</strong></Text>
                <Text>
                    We may update these Terms from time to time. Continued use of the service after changes are made constitutes acceptance of the revised Terms.
                </Text>

                <Text><strong>12. Contact</strong></Text>
                <Text>
                    For any questions about these Terms, please contact us at <a href="mailto:support@vivamind.com" style={{ color: 'teal' }}>support@vivamind.com</a>.
                </Text>
            </VStack>
        </Box>
    );
}

export default TermsOfService;